### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/delivery-carrier#106]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] base_delivery_carrier_files - By @thomaspaulb - #206 
- [ ] base_delivery_carrier_files_document - ~~By @mFlayyan - #184~~ By @thomaspaulb - #206 
- [ ] base_delivery_carrier_label  #124 @angelmoya
- [x] delivery_carrier_b2c https://github.com/OCA/delivery-carrier/pull/116 @EBII
- [ ] delivery_carrier_deposit - By @EBII - #133 
- [ ] delivery_carrier_file_laposte
- [ ] delivery_carrier_file_tnt
- [ ] delivery_carrier_label_default - By @thomaspaulb - #207 
- [ ] delivery_carrier_label_dispatch
- [ ] delivery_carrier_label_gls
- [ ] delivery_carrier_label_postlogistics @yvaucher
- [ ] delivery_carrier_label_postlogistics_shop_logo
- [ ] delivery_optional_invoice_line
