### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/delivery-carrier#139]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] base_delivery_carrier_files
- [ ] base_delivery_carrier_files_document
- [x] base_delivery_carrier_label - ~~By @hugosantosred - #150~~ By @asaunier - #154 
- [ ] delivery_carrier_b2c
- [ ] delivery_carrier_deposit
- [ ] delivery_carrier_file_laposte
- [ ] delivery_carrier_file_tnt
- [x] delivery_carrier_label_default - By @sebalix - #169 
- [ ] delivery_carrier_label_default_webkit
- [ ] delivery_carrier_label_dispatch
- [ ] delivery_carrier_label_gls
- [ ] delivery_carrier_label_postlogistics - By @grindtildeath - #155 
- [ ] delivery_carrier_label_postlogistics_shop_logo
- [x] delivery_carrier_partner - By @SimoRubi - #172 
- [ ] delivery_multi_destination
- [ ] delivery_optional_invoice_line
- [x] delivery_price_rule_untaxed - By @tarteo - #173 
- [ ] sale_delivery_rate
- [ ] stock_picking_delivery_rate

**Comment by emagdalenaC2i** [comment]
@pedrobaeza base_delivery_carrier_label is done
