### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/delivery-carrier#534]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] base_delivery_carrier_label - By @florian-dacosta - #570
- [x] carrier_account_environment - By @florian-dacosta - #616
- [x] delivery_auto_refresh - By @RabbitJon-S73 - #651
- [x] delivery_carrier_agency - By @florian-dacosta - #571
- [ ] delivery_carrier_default_tracking_url - By @gaelTorrecillas - #679
- [x] delivery_carrier_deposit - By @clementmbr - #764
- [x] delivery_carrier_info - By @florian-dacosta - #568
- [ ] delivery_carrier_label_gls - By @glitchov - #599
- [x] delivery_carrier_max_weight_constraint - By @glitchov - #594
- [x] delivery_carrier_multi_zip - By @victoralmau - #1055
- [x] delivery_carrier_package_measure_required - By @RodrigoBM - #713
- [x] delivery_carrier_partner - By @glitchov - #640
- [ ] delivery_carrier_pricelist - By @AnizR - #824
- [ ] delivery_carrier_service_level - By @ntsirintanis - #607
- [x] delivery_correos_express - By @vicentecom - #813
- [x] delivery_cttexpress - By @chienandalu - #566
- [x] delivery_dropoff_site - By @jdoutreloux - #754
- [x] delivery_multi_destination - By @carolinafernandez-tecnativa - #766
- [x] delivery_package_fee - By @tuantrantg - #693
- [x] delivery_package_number - By @chienandalu - #553
- [x] delivery_postlogistics - By @lehoangan - #619
- [x] delivery_price_method - By @chienandalu - #554
- [x] delivery_purchase - By @carolinafernandez-tecnativa - #755
- [x] delivery_roulier_laposte_fr - By @chafique-delli - #836
- [x] delivery_roulier_option - By @chafique-delli - #837
- [x] delivery_state - By @chienandalu - #551
- [ ] delivery_tnt_oca - By @hildickethan-S73 - #649
- [ ] delivery_translatable - By @David-Luis-Mora - #800
- [ ] partner_default_delivery_carrier - By @BT-mrobles - #727
- [x] partner_delivery_schedule - By @victoralmau - #770
- [x] partner_delivery_zone - By @gerardoOperu - #648
- [x] stock_picking_delivery_link - By @glitchov - #596
- [x] stock_picking_report_delivery_cost - By @victoralmau - #706

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by lehoangan** [comment]
- delivery_postlogistics: [#619](https://github.com/OCA/delivery-carrier/pull/619)

**Comment by lehoangan** [comment]
- delivery_postlogistics_server_env : [#620 ](https://github.com/OCA/delivery-carrier/pull/620)

**Comment by ferran-S73** [comment]
- delivery_schenker: https://github.com/OCA/delivery-carrier/pull/632

**Comment by RabbitJon-S73** [comment]
- delivery_auto_refresh: https://github.com/OCA/delivery-carrier/pull/651

**Comment by BT-mrobles** [comment]
- partner_default_delivery_carrier: https://github.com/OCA/delivery-carrier/pull/727

**Comment by OscarIndias** [comment]
- delivery_deliverea: https://github.com/OCA/delivery-carrier/pull/657

**Comment by RodrigoBM** [comment]
- delivery_carrier_package_measure_required: https://github.com/OCA/delivery-carrier/pull/713

**Comment by David-Luis-Mora** [comment]
Working in delivery_translatable: #800
