### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/delivery-carrier#71]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] base_delivery_carrier_files > base_delivery_carrier_file - By @angelmoya - #129 
- [ ] base_delivery_carrier_files_document
- [x] base_delivery_carrier_label @yvaucher https://github.com/OCA/carrier-delivery/pull/72
- [ ] delivery_carrier_b2c
- [x] delivery_carrier_deposit - By @hparfr - #114 
- [ ] delivery_carrier_file_laposte
- [ ] delivery_carrier_file_tnt
- [ ] delivery_carrier_label_default_webkit
- [x] delivery_carrier_label_dispatch renamed delivery_carrier_label_batch @yvaucher #99 
- [ ] delivery_carrier_label_gls
- [x] delivery_carrier_label_postlogistics @yvaucher https://github.com/OCA/carrier-delivery/pull/73
- [ ] delivery_carrier_label_postlogistics_shop_logo
- [ ] delivery_dropoff_site - By @lmignon - #209 (Backport from 10.0)
- [ ] delivery_optional_invoice_line
